// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr8oXXAf1u43fpNlGRe9DhRywXbbYLSDQ',
    appId: '1:373024261802:web:48a1435fb634a1318072d3',
    messagingSenderId: '373024261802',
    projectId: 'firestore-database-9ee6c',
    authDomain: 'firestore-database-9ee6c.firebaseapp.com',
    storageBucket: 'firestore-database-9ee6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ_aV73XZoRAsH9HXmE20YVKqQ69NKmNM',
    appId: '1:373024261802:android:04b56eaf7a606de78072d3',
    messagingSenderId: '373024261802',
    projectId: 'firestore-database-9ee6c',
    storageBucket: 'firestore-database-9ee6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJGg3CMn5ZMCSAwlLj-SBxsb6IcUQGNTg',
    appId: '1:373024261802:ios:120e74dba6db830c8072d3',
    messagingSenderId: '373024261802',
    projectId: 'firestore-database-9ee6c',
    storageBucket: 'firestore-database-9ee6c.appspot.com',
    iosBundleId: 'com.example.firestoreDatabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr8oXXAf1u43fpNlGRe9DhRywXbbYLSDQ',
    appId: '1:373024261802:web:181d42cee1917cf48072d3',
    messagingSenderId: '373024261802',
    projectId: 'firestore-database-9ee6c',
    authDomain: 'firestore-database-9ee6c.firebaseapp.com',
    storageBucket: 'firestore-database-9ee6c.appspot.com',
  );
}
